dist: trusty

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - ./peddle-webapp/node_modules/

before_script:
  - npm install --prefix ./peddle-webapp/
script:
  - mvn clean test
  - npm run build --prefix ./peddle-webapp/