export const FETCH_EVENTS_START = 'FETCH_EVENTS_START'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE'

export const LOAD_MORE_EVENTS_START = 'LOAD_MORE_EVENTS_START'
export const LOAD_MORE_EVENTS_SUCCESS = 'LOAD_MORE_EVENTS_SUCCESS'
export const LOAD_MORE_EVENTS_FAILURE = 'LOAD_MORE_EVENTS_FAILURE'

export const FETCH_EVENT_BY_ID_START = 'FETCH_EVENT_BY_ID_START'
export const FETCH_EVENT_BY_ID_SUCCESS = 'FETCH_EVENT_BY_ID_SUCCESS'
export const FETCH_EVENT_BY_ID_FAILURE = 'FETCH_EVENT_BY_ID_FAILURE'

export const ADD_EVENT_TO_BASKET = 'ADD_EVENT_TO_BASKET'

export const SEARCH_EVENT = 'SEARCH_EVENT'

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'

export const REMOVE_EVENT_FROM_BASKET = 'REMOVE_EVENT_FROM_BASKET'

export const CLEAN_BASKET = 'CLEAN_BASKET'
