export const CHOSEN_EVENT = 'CHOSEN_EVENT';
export const LOAD_EVENT_INFO='LOAD_EVENT_INFO';
export const USER_LOGIN = 'USER_LOGIN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOAD_WISHLIST = 'LOAD_WISHLIST';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const LOAD_PURCHASE_LIST = 'LOAD_PURCHASE_LIST';
export const ADD_TO_PURCHASES = 'ADD_TO_PURCHASES';
export const FILL_CITIES_LIST = "FILL_CITIES_LIST";
export const FILL_CATEGORIES_LIST = "FILL_CATEGORIES_LIST";

export const SET_CITY_FOR_TRANSFER_FROM_EVENT = 'SET_CITY_FOR_TRANSFER_FROM_EVENT';
export const SET_CITY_FOR_TRANSFER_TO_EVENT = 'SET_CITY_FOR_TRANSFER_TO_EVENT';
export const SET_EVENT_CITY = 'SET_EVENT_CITY';
export const SET_DATE_TRANSFER_TO_EVENT = 'SET_DATE_TRANSFER_TO_EVENT';
export const SET_DATE_TRANSFER_FROM_EVENT = 'SET_DATE_TRANSFER_FROM_EVENT';
export const SET_DAYS_BEFORE_EVENT_INC ='SET_DAYS_BEFORE_EVENT_INC';
export const SET_DAYS_BEFORE_EVENT_DEC ='SET_DAYS_BEFORE_EVENT_DEC';
export const SET_DAYS_AFTER_EVENT_INC ='SET_DAYS_AFTER_EVENT_INC';
export const SET_DAYS_AFTER_EVENT_DEC ='SET_DAYS_AFTER_EVENT_DEC';
export const LOAD_TRANSFERS_FORWARD = 'LOAD_TRANSFERS_FORWARD';
export const LOAD_TRANSFERS_BACKWARD = 'LOAD_TRANSFERS_BACKWARD';

export const LOAD_EVENTS = 'LOAD_EVENTS';
export const LOAD_TOP_EVENTS = 'LOAD_TOP_EVENTS';
export const SET_FETCH_PENDING = 'SET_FETCH_PENDING';
export const SET_FETCH_SUCCESS = 'SET_FETCH_SUCCESS';
export const SET_FETCH_ERROR = 'SET_FETCH_ERROR';

export const SET_EVENT_INFO_PENDING = 'SET_EVENT_INFO_PENDING';
export const SET_EVENT_INFO_SUCCESS = 'SET_EVENT_INFO_SUCCESS';
export const SET_EVENT_INFO_ERROR = 'SET_EVENT_INFO_ERROR';

export const SET_FILTER_CATEGORY = 'SET_FILTER_CATEGORY';
export const SET_FILTER_CITY = 'SET_FILTER_CITY';
export const SET_FILTER_DATE_FROM = 'SET_FILTER_DATE_FROM';
export const SET_FILTER_DATE_TO = 'SET_FILTER_DATE_TO';
export const FILTER_RESET = 'FILTER_RESET';
