export const CHOSEN_EVENT = 'CHOSEN_EVENT';
export const LOAD_EVENT_INFO = 'LOAD_EVENT_INFO';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_UPDATE = 'USER_UPDATE';
export const SET_REGISTER_PENDING = 'SET_REGISTER_PENDING';
export const SET_REGISTER_ERROR = 'SET_REGISTER_ERROR';
export const SET_REGISTER_SUCCESS = 'SET_REGISTER_SUCCESS';
export const SET_UPDATE_PROFILE_PENDING = 'SET_UPDATE_PROFILE_PENDING';
export const SET_UPDATE_PROFILE_ERROR = 'SET_UPDATE_PROFILE_ERROR';
export const SET_UPDATE_PROFILE_SUCCESS = 'SET_UPDATE_PROFILE_SUCCESS';

export const LOGGED_IN = 'LOGGED_IN';
export const LOAD_WISHLIST = 'LOAD_WISHLIST';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const LOAD_PURCHASE_LIST = 'LOAD_PURCHASE_LIST';
export const ADD_TO_PURCHASES = 'ADD_TO_PURCHASES';
export const FILL_CITIES_LIST = "FILL_CITIES_LIST";
export const FILL_CATEGORIES_LIST = "FILL_CATEGORIES_LIST";
export const FILL_LANGUAGES_LIST = "FILL_LANGUAGES_LIST";

export const SET_LOAD_ACCOMMODATION_PENDING = 'SET_LOAD_ACCOMMODATION_PENDING';
export const SET_LOAD_ACCOMMODATION_SUCCESS = 'SET_LOAD_ACCOMMODATION_SUCCESS';
export const SET_LOAD_ACCOMMODATION_ERROR = 'SET_LOAD_ACCOMMODATION_ERROR';
export const LOAD_ACCOMMODATIONS = 'LOAD_ACCOMMODATIONS';
export const SET_ACCOMMODATIONS = 'SET_ACCOMMODATIONS';

export const SET_CITY_FOR_TRANSFER_FROM_EVENT = 'SET_CITY_FOR_TRANSFER_FROM_EVENT';
export const SET_CITY_FOR_TRANSFER_TO_EVENT = 'SET_CITY_FOR_TRANSFER_TO_EVENT';
export const SET_EVENT_CITY = 'SET_EVENT_CITY';
export const SET_DATE_TRANSFER_TO_EVENT = 'SET_DATE_TRANSFER_TO_EVENT';
export const SET_DATE_TRANSFER_FROM_EVENT = 'SET_DATE_TRANSFER_FROM_EVENT';
export const SET_DAYS_BEFORE_EVENT_INC = 'SET_DAYS_BEFORE_EVENT_INC';
export const SET_DAYS_BEFORE_EVENT_DEC = 'SET_DAYS_BEFORE_EVENT_DEC';
export const SET_DAYS_AFTER_EVENT_INC = 'SET_DAYS_AFTER_EVENT_INC';
export const SET_DAYS_AFTER_EVENT_DEC = 'SET_DAYS_AFTER_EVENT_DEC';
export const RESET_DAYS_DELTA = 'RESET_DAYS_DELTA';
export const LOAD_TRANSFERS_FORWARD = 'LOAD_TRANSFERS_FORWARD';
export const LOAD_TRANSFERS_BACKWARD = 'LOAD_TRANSFERS_BACKWARD';
export const SET_TRANSFERS_FORWARD_PENDING = 'SET_TRANSFERS_FORWARD_PENDING';
export const SET_TRANSFERS_FORWARD_SUCCESS = 'SET_TRANSFERS_FORWARD_SUCCESS';
export const SET_TRANSFERS_FORWARD_ERROR = 'SET_TRANSFERS_FORWARD_ERROR';
export const SET_TRANSFERS_BACKWARD_PENDING = 'SET_TRANSFERS_BACKWARD_PENDING';
export const SET_TRANSFERS_BACKWARD_SUCCESS = 'SET_TRANSFERS_BACKWARD_SUCCESS';
export const SET_TRANSFERS_BACKWARD_ERROR = 'SET_TRANSFERS_BACKWARD_ERROR';

export const LOAD_EVENTS = 'LOAD_EVENTS';
export const LOAD_TOP_EVENTS = 'LOAD_TOP_EVENTS';
export const SET_FETCH_PENDING = 'SET_FETCH_PENDING';
export const SET_FETCH_SUCCESS = 'SET_FETCH_SUCCESS';
export const SET_FETCH_ERROR = 'SET_FETCH_ERROR';

export const SET_EVENT_INFO_PENDING = 'SET_EVENT_INFO_PENDING';
export const SET_EVENT_INFO_SUCCESS = 'SET_EVENT_INFO_SUCCESS';
export const SET_EVENT_INFO_ERROR = 'SET_EVENT_INFO_ERROR';

export const SET_FILTER_CATEGORY = 'SET_FILTER_CATEGORY';
export const SET_FILTER_CITY = 'SET_FILTER_CITY';
export const SET_FILTER_DATE_FROM = 'SET_FILTER_DATE_FROM';
export const SET_FILTER_DATE_TO = 'SET_FILTER_DATE_TO';
export const FILTER_RESET = 'FILTER_RESET';

export const ADD_EVENT_TO_CART = 'ADD_EVENT_TO_CART';
export const ADD_ACCOMMODATION_TO_CART = 'ADD_ACCOMMODATION_TO_CART';
export const ADD_TRANSFER_TO_EVENT_TO_CART = 'ADD_TRANSFER_TO_EVENT_TO_CART';
export const ADD_TRANSFER_FROM_EVENT_TO_CARD = 'TRANSFER_FROM_EVENT_TO_CARD';
export const ADD_TRANSLATOR_TO_CART = 'ADD_TRANSLATOR_TO_CART';
export const ADD_PHOTOGRAPHER_TO_CART = 'ADD_PHOTOGRAPHER_TO_CART';