export const EVENTS_FILTER = 'EVENTS_FILTER';
export const CHOSEN_EVENT = 'CHOSEN_EVENT';
export const USER_LOGIN = 'USER_LOGIN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOAD_WISHLIST = 'LOAD_WISHLIST';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const LOAD_PURCHASE_LIST = 'LOAD_PURCHASE_LIST';





